apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rook-log
spec:
#  storageClassName: rook-ceph-block
  storageClassName: rook-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
